version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  version: 3.9
  setup_py_install: false  # Disable setup.py installation
  extra_requirements:
    - docs

# Use Poetry for installing dependencies
poetry: true
