site_name: Curso_Open_science_Tristan documentation
nav:
  - Home: README.md
theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true